import Head from 'next/head'
import { useEffect } from "react"

import styles from '@/styles/Home.module.css'

export default function Home()
{
  useEffect(() =>
  {
    window.location.replace("/login")
  }, [])

  return (
    <>
      <Head>
        <title>Sistema de Consulta - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
